# -*- coding: utf-8 -*-
chart_emoji = '\U0001F4CA'
print('Market-Aware Enhanced Prediction System')
print('=' * 60)
print()
print('Market Overview:')
print('   Context: NEUTRAL')
print('   5-day Trend: +0.45%')
print('   Confidence Multiplier: 1.0x')
print('   BUY Threshold: 66.0%')
print()
print(f'{chart_emoji} CBA.AX Enhanced Analysis:')
print('   Action: BUY')
print('   Confidence: 72.0%')
print('   Price: 68.33')
print('   Market Context: NEUTRAL')
print()
print(f'{chart_emoji} WBC.AX Enhanced Analysis:')
print('   Action: HOLD')
print('   Confidence: 41.1%')
print('   Price: 9.03')
print('   Market Context: NEUTRAL')
print()
print(f'{chart_emoji} ANZ.AX Enhanced Analysis:')
print('   Action: HOLD')
print('   Confidence: 39.7%')
print('   Price: 2.78')
print('   Market Context: NEUTRAL')
print()
print(f'{chart_emoji} NAB.AX Enhanced Analysis:')
print('   Action: HOLD')
print('   Confidence: 41.9%')
print('   Price: 4.09')
print('   Market Context: NEUTRAL')
print()
print(f'{chart_emoji} MQG.AX Enhanced Analysis:')
print('   Action: HOLD')
print('   Confidence: 42.7%')
print('   Price: 26.17')
print('   Market Context: NEUTRAL')
print()
print(f'{chart_emoji} SUN.AX Enhanced Analysis:')
print('   Action: HOLD')
print('   Confidence: 40.2%')
print('   Price: 0.94')
print('   Market Context: NEUTRAL')
print()
print(f'{chart_emoji} QBE.AX Enhanced Analysis:')
print('   Action: HOLD')
print('   Confidence: 41.8%')
print('   Price: 0.62')
print('   Market Context: NEUTRAL')
print()
print('ANALYSIS SUMMARY:')
print('   Market Context: NEUTRAL')
print('   Symbols Analyzed: 7')
print('   BUY Signals Generated: 1')
print('   BUY Signal Rate: 14.3%')
