# USA Machine Learning Configuration
# Regional ML settings specific to US financial markets

# Data Sources Configuration
data_sources:
  primary_source: "yahoo_finance"
  backup_sources: ["alpha_vantage", "marketaux", "bloomberg"]
  symbol_suffix: ""  # No suffix for US stocks
  
  # US-specific data requirements
  minimum_data_points: 252  # 1 trading year
  lookback_period_days: 1260  # 5 years
  validation_split: 0.2
  test_split: 0.1

# Feature Engineering for US Markets
feature_engineering:
  # Technical indicators optimized for US market volatility
  technical_indicators:
    # Trend indicators
    sma_periods: [5, 10, 20, 50, 200]
    ema_periods: [12, 26, 50]
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    
    # Momentum indicators
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    
    # Volatility indicators (higher volatility than ASX)
    bollinger_bands:
      period: 20
      std_dev: 2.5  # Wider bands for US volatility
    atr_period: 14
    
    # Volume indicators (very important in US markets)
    volume_sma_periods: [10, 20]
    volume_ratio_period: 20
    vwap: true  # Volume Weighted Average Price
    
  # US-specific market features
  market_features:
    # Market cap considerations (broader range)
    market_cap_buckets: ["mega_cap", "large_cap", "mid_cap", "small_cap"]
    
    # Sector relationships (US financial focus)
    sector_correlation: true
    financial_sector_weight: 0.7  # Slightly lower than ASX
    
    # Currency impact (USD strength - inverse of others)
    usd_strength_correlation: true
    dxy_correlation: true  # Dollar Index correlation
    
    # Interest rate sensitivity (Fed policy critical)
    interest_rate_sensitivity: true
    fed_policy_impact: true
    treasury_yield_correlation: true
    
    # US-specific factors
    earnings_season_impact: 1.5
    fomc_meeting_impact: 2.0
    economic_data_impact: 1.3

  # News sentiment features
  sentiment_features:
    sentiment_window_hours: 24
    news_quality_weight: true
    source_tier_importance: [1.0, 0.9, 0.7, 0.5]  # 4-tier system
    
    # US-specific sentiment factors
    sec_filing_weight: 1.4
    earnings_announcement_weight: 1.6
    fed_announcement_weight: 2.0
    analyst_rating_weight: 1.2

# Model Configurations
models:
  # Random Forest (Primary Model)
  random_forest:
    enabled: true
    n_estimators: 300  # More trees for US complexity
    max_depth: 18
    min_samples_split: 4
    min_samples_leaf: 2
    max_features: "sqrt"
    bootstrap: true
    
    # US-specific parameters
    class_weight: "balanced_subsample"  # Handle imbalanced data better
    oob_score: true
    n_jobs: -1
    
  # Gradient Boosting (Secondary Model)
  gradient_boosting:
    enabled: true
    n_estimators: 200  # More for complex US patterns
    learning_rate: 0.08  # Slightly lower for stability
    max_depth: 10
    subsample: 0.85
    
    # Early stopping for US volatility
    validation_fraction: 0.15
    n_iter_no_change: 15
    
  # XGBoost (Additional Model for US markets)
  xgboost:
    enabled: true
    n_estimators: 250
    learning_rate: 0.1
    max_depth: 8
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0
    
  # LSTM (Advanced Model)
  lstm:
    enabled: false  # Disabled initially
    sequence_length: 30
    hidden_units: [256, 128, 64]  # Larger for US complexity
    dropout_rate: 0.4  # Higher dropout for regularization
    learning_rate: 0.0008
    batch_size: 64
    epochs: 150
    
  # Ensemble Configuration
  ensemble:
    enabled: true
    voting_method: "soft"
    weights:
      random_forest: 0.4
      gradient_boosting: 0.3
      xgboost: 0.3
      lstm: 0.0  # Disabled initially

# Training Configuration
training:
  # Cross-validation strategy
  cross_validation:
    method: "time_series_split"
    n_splits: 6  # More splits for US data
    test_size_ratio: 0.15
    gap: 5  # Gap between train/test to avoid lookahead
    
  # Hyperparameter tuning
  hyperparameter_tuning:
    enabled: true
    method: "random_search"  # More efficient than grid search
    n_iter: 100  # Number of parameter combinations
    cv_folds: 4
    scoring: "f1_weighted"
    
    # Random search parameters
    param_distributions:
      random_forest:
        n_estimators: [200, 300, 400]
        max_depth: [15, 18, 20, 25]
        min_samples_split: [2, 4, 6]
        min_samples_leaf: [1, 2, 3]
        
      gradient_boosting:
        n_estimators: [150, 200, 250]
        learning_rate: [0.05, 0.08, 0.1, 0.12]
        max_depth: [8, 10, 12]
        subsample: [0.8, 0.85, 0.9]

  # Feature selection
  feature_selection:
    enabled: true
    method: "recursive_feature_elimination"
    n_features_to_select: 25  # More features for US complexity
    step: 2
    cross_validation: true
    
  # Model persistence
  model_persistence:
    save_models: true
    model_versioning: true
    backup_models: true
    compression: true
    save_feature_importance: true

# Prediction Configuration
prediction:
  # Classification targets
  targets:
    primary: "action"  # BUY, SELL, HOLD
    secondary: "confidence"
    tertiary: "volatility_estimate"
    
  # Class definitions (adjusted for US market volatility)
  classes:
    STRONG_BUY:
      threshold: 0.90  # Higher threshold for US markets
      description: "Very strong buy signal"
    BUY: 
      threshold: 0.75  # Higher than ASX
      description: "Buy signal"
    HOLD:
      threshold: [0.25, 0.75]  # Wider neutral zone
      description: "Hold/neutral position"
    SELL:
      threshold: 0.25
      description: "Sell signal"
    STRONG_SELL:
      threshold: 0.10
      description: "Strong sell signal"
      
  # Confidence scoring
  confidence_calculation:
    method: "probability_margin_with_volatility"
    min_confidence: 0.1
    max_confidence: 1.0
    volatility_adjustment: true
    
  # Risk adjustment for US markets
  risk_adjustment:
    volatility_penalty: 0.15  # Higher than ASX
    liquidity_boost: 0.03  # Lower boost (high liquidity assumed)
    market_cap_factor: true
    regulatory_risk_factor: true

# Evaluation Metrics
evaluation:
  # Primary metrics
  primary_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"
    
  # Financial metrics
  financial_metrics:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "calmar_ratio"
    
  # US-specific evaluation
  us_metrics:
    - "sector_performance"
    - "fed_cycle_performance"
    - "earnings_season_performance"
    - "market_regime_analysis"
    
  # Backtesting configuration
  backtesting:
    start_date: "2019-01-01"  # 6 years of backtesting
    end_date: "2025-01-01"
    initial_capital: 100000  # USD $100K
    transaction_costs: 0.002  # 0.2% per trade (higher than ASX)
    max_positions: 8  # More positions for diversification
    rebalance_frequency: "weekly"
    benchmark: "SPY"  # S&P 500 benchmark

# Data Quality Standards
data_quality:
  # Missing data handling
  missing_data:
    max_missing_percentage: 0.03  # Stricter for US markets
    imputation_method: "forward_fill_with_interpolation"
    consecutive_missing_limit: 3
    
  # Outlier detection
  outlier_detection:
    method: "isolation_forest"
    contamination: 0.05  # Lower contamination threshold
    
  # Data validation
  validation_rules:
    price_change_limit: 0.15  # 15% daily change limit
    volume_spike_threshold: 8.0  # 8x average volume
    gap_detection: true
    
  # US-specific validations
  us_validations:
    circuit_breaker_detection: true
    halted_stock_detection: true
    earnings_announcement_detection: true

# Performance Optimization
performance:
  # Memory management
  memory_optimization:
    chunk_size: 2000  # Larger chunks for US data volume
    lazy_loading: true
    garbage_collection: true
    memory_mapping: true
    
  # Parallel processing
  parallel_processing:
    n_jobs: -1
    backend: "loky"
    prefer_threads_for_io: true
    
  # Caching
  caching:
    feature_cache: true
    model_cache: true
    prediction_cache: true
    cache_ttl_hours: 12  # Shorter TTL for fast-moving US markets
    redis_caching: true

# Regional Specific Settings
regional_settings:
  timezone: "America/New_York"
  currency: "USD"
  
  # US trading calendar
  trading_calendar:
    market_open: "09:30"
    market_close: "16:00"
    early_close_time: "13:00"
    extended_hours: true
    
  # Regulatory considerations
  regulatory:
    pattern_day_trading_rules: true
    wash_sale_rules: true
    short_sale_restrictions: true
    circuit_breakers: true
    
  # Market microstructure
  market_structure:
    tick_size: 0.01
    lot_size: 1
    settlement_cycle: "T+2"
    dark_pools: true
    high_frequency_trading: true

# Logging and Monitoring
logging:
  level: "INFO"
  format: "json"
  
  # Model performance monitoring
  model_monitoring:
    track_drift: true
    performance_degradation_threshold: 0.03  # Stricter
    retrain_threshold: 0.08
    concept_drift_detection: true
    
  # Feature monitoring
  feature_monitoring:
    track_importance: true
    stability_threshold: 0.05  # Stricter stability
    correlation_monitoring: true
    
# Model Deployment
deployment:
  # Model serving
  model_serving:
    batch_prediction: true
    real_time_prediction: true  # Enabled for US markets
    api_endpoints: true
    
  # Model updates
  model_updates:
    retrain_frequency: "bi-weekly"  # More frequent for US markets
    auto_retrain: false
    champion_challenger: true
    
  # A/B testing
  ab_testing:
    enabled: true
    traffic_split: 0.2
    statistical_significance: 0.05
    
# Integration Settings
integration:
  # Database connections
  database:
    primary: "postgresql"  # More robust for US scale
    backup: "sqlite"
    time_series_db: "influxdb"
    
  # External APIs
  external_apis:
    yahoo_finance: true
    alpha_vantage: true
    marketaux: true
    bloomberg: true
    quandl: true
    
  # Microservices
  microservices:
    prediction_service: true
    market_data_service: true
    sentiment_service: true
    risk_management_service: true
